---
stages:
  - test
  - build
  - deploy
  - lint

job-test:
  stage: test
  tags:
    - docker
  script:
    - echo "This job test app"

job-lint:
  stage: lint
  image: hadolint/hadolint:2.10.0
  tags:
    - docker
  script:
    - docker run --rm -i hadolint/hadolint:2.10.0 < .deploy/docker/Dockerfile

job-build:
  stage: build
  tags:
    - docker
  script:
    - docker login --username "$DOCKER_NAME" --password "$DOCKER_PS"
    - docker info
    - docker build /builds/simbirsoft1/devops-workshop-2023-12/prishedko.egor/exercise-03/.deploy/docker/ -t egor140512/exercise:${CI_COMMIT_SHORT_SHA}
    - docker push egor140512/exercise:0.5.1
    - docker logout
    - docker info
  after_script:
    - docker info

job-deploy:
  stage: deploy
  image: bitnami/kubectl:1.26.12
  tags:
    - docker
  before_script:
    - kubectl get nodes
  script:
    - kind create cluster --config kind.yaml -n simbir
    - kubectl apply -f ns.yaml
    - kubectl apply -f postgresql.yaml
    - kubectl apply -f application.yaml
    - kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
after_script:
  - echo "deploy finished"
