---
stages:
  - lint
  - build
  - deploy

job-lint:
  stage: lint
  image: hadolint/hadolint
  script:
    - docker run --rm -i hadolint/hadolint < .deploy/docker/Dockerfile

job-build:
  stage: build
  script:
    - echo "This job build something"

job-deploy:
  stage: deploy
  script:
    - echo "This job deploy something"